"""Hatchling custom build hook — inject git SHA + build timestamp into athena/core/_version.py.

This is the ONLY sanctioned source of POLICY_VERSION_SHA (AR-COM4 / Story 1.1 AC-5).
The hook runs once during `uv build` / `hatch build`, calls `git describe --always --dirty`,
and writes a static `_version.py` consumed by `athena.core.version` at runtime.
Runtime subprocess calls are forbidden — see test_version_no_shell.py.
"""

from __future__ import annotations

import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CustomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        commit = self._git_describe(Path(self.root).resolve())
        build_time = datetime.now(UTC).isoformat()

        version_file = Path(self.root) / "athena" / "core" / "_version.py"
        version_file.parent.mkdir(parents=True, exist_ok=True)
        # repr() produces a safely-quoted Python string literal even if the upstream
        # value ever contains a stray quote or backslash (defense-in-depth).
        version_file.write_text(
            "# AUTO-GENERATED by hatch_build.py - DO NOT EDIT\n"
            f"__commit__: str = {commit!r}\n"
            f"__build_time_utc__: str = {build_time!r}\n",
            encoding="utf-8",
        )

    @staticmethod
    def _git_describe(repo_root: Path) -> str:
        try:
            result = subprocess.run(
                ["git", "describe", "--always", "--dirty"],
                cwd=str(repo_root),
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                check=False,
                timeout=10,
            )
            output = result.stdout.strip()
            if result.returncode == 0 and output:
                return output
        except (FileNotFoundError, subprocess.SubprocessError, OSError, UnicodeDecodeError):
            pass
        return "unknown-dev"
